### ISSUE TITLE
I can't download using Maven.

### ISSUE THREAD

**Issue by chengzhiqiangqg** [codewriterbv/lemonsqueezy-java#2]
![image](https://github.com/user-attachments/assets/c40ca6c3-b54d-4d86-97ff-b52e69cf0a46)

**Comment by FDelporte** [comment]
Indeed, this is work-in-progress, so for now it's only available from GitHub packages as described here:
https://github.com/codewriterbv/lemonsqueezy-java?tab=readme-ov-file#using-this-library-in-your-project

What functionality do you exactly need as this project is in early stage...

**Comment by chengzhiqiangqg** [comment]
Create a checkout   、Retrieve a checkout、Callback

**Comment by FDelporte** [comment]
If you mean "webhooks" with "callback", these are available: https://github.com/codewriterbv/lemonsqueezy-java/blob/main/src/main/java/be/codewriter/lemonsqueezy/webhook/WebhookMessage.java and I use them on https://melodymatrix.rocks/.

Can you validate this already with the GitHub package?

**Comment by chengzhiqiangqg** [comment]
Thank you very much

**Comment by FDelporte** [comment]
I added checkout objects, not fully unit tested, but for you to try out. New build should now be available with these new objects:

https://github.com/codewriterbv/lemonsqueezy-java/commit/0be0959294ec70db55cd128c8495d4571b61b135

**Comment by chengzhiqiangqg** [comment]
kindly beg your update

**Comment by FDelporte** [comment]
As you can see here, there is a new build lemonsqueezy-java-0.0.1-20240719
https://github.com/codewriterbv/lemonsqueezy-java/packages/2189280

If you downloaded it before, you'll need to remove if from your local .m2 repository cache

**Comment by chengzhiqiangqg** [comment]
![image](https://github.com/user-attachments/assets/f63108ee-71cd-4e27-a30d-99f262d48f9f)
Thank you very much， The test passed.  Could you please guide me on how to add an api_key along with other parameters? I would really appreciate your help with this.

**Comment by chengzhiqiangqg** [comment]
CheckoutAttributes attr = checkout.getAttributes();   That would be to encapsulate the api_key and attr into the request object and then initiate the request, right?

**Comment by chengzhiqiangqg** [comment]
![image](https://github.com/user-attachments/assets/3f0a1c73-a819-46b8-bf22-555b525edd11)
![image](https://github.com/user-attachments/assets/4117e2a0-0956-4fb0-b9a4-164b4f402125)
![image](https://github.com/user-attachments/assets/a0d5f041-bb95-4556-821b-2b9adada353e)
Missing data

**Comment by FDelporte** [comment]
These relationships: 
https://github.com/codewriterbv/lemonsqueezy-java/blob/main/src/test/resources/lemonsqueezy/checkout/checkout_response.json#L69
Are tested here OK:
https://github.com/codewriterbv/lemonsqueezy-java/blob/main/src/test/java/be/codewriter/lemonsqueezy/checkout/CheckoutTest.java#L77

Can you maybe give additional info, example JSON, or maybe even do merge request to extend the code?

**Comment by chengzhiqiangqg** [comment]
"The JSON data in the example request to the right of 'Create a checkout' on the linked page [https://docs.lemonsqueezy.com/api/checkouts#create-a-checkout](https://docs.lemonsqueezy.com/api/checkouts#create-a-checkout)."
![IMG_3127](https://github.com/user-attachments/assets/cdee0ded-5abd-4daa-bcdc-2625cd72e60f)

**Comment by FDelporte** [comment]
Please check this: https://github.com/codewriterbv/lemonsqueezy-java/blob/main/src/test/java/be/codewriter/lemonsqueezy/checkout/CheckoutTest.java#L94

But not all unit tests are finished, so be aware, e.g., timestamp parsing is not correct yet!

**Comment by chengzhiqiangqg** [comment]
Kindly request your update

**Comment by FDelporte** [comment]
@chengzhiqiangqg this is an API GET example: https://github.com/codewriterbv/lemonsqueezy-java/commit/27df23b9fd9c491ab24f7f9a2252324005bbebb0#diff-2ba47f4534a1a17e4bdb90921a0f744f4245312b0f923b00155f7aa337e7ad2bR16

**Comment by FDelporte** [comment]
Hi @chengzhiqiangqg do you have everything you need with the current version?

**Comment by FDelporte** [comment]
A very early version is now available on Maven:
https://central.sonatype.com/artifact/be.codewriter/lemonsqueezy-java
